### ISSUE TITLE
Can I translate some of your blog posts in Chinese?

### ISSUE THREAD

**Issue by weakish** [hardmaru/rnn-tutorial#1]
Hi.

A lot of articles in your blog are greatly comprehensible, with cute images.
I'd like to translate them to Chinese, making them more approachable to Chinese ML developers.

I am currently working for a Chinese new media about AI and machine learning.
I am looking forward to know:

Is it O.K. to publish the translation on the WeChat social public account of the media/company,
and on the website later in future (the website is under construction),
or what is the license of your blog posts?

And if you have any specific requirements, or questions, please let me know.

Thanks.

P.S. The WeChat account name is [论智][zhi], basically means "on intelligence" in Chinese.

[zhi]: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzI3ODkxODU3Mg==&scene=124

**Comment by hardmaru** [comment]
Hi @weakish,

Thanks for offering to translate the blog post to Chinese.

In the past, another one of my blog posts has been translated to Japanese and Chinese. This is the one:

original: http://blog.otoro.net/2015/05/07/creatures-avoiding-planks/
translation: http://www.wukai.me/2016/03/01/creatures-avoiding-planks/

I'm certainly okay for you to translate it, but can you include links and attributions like the translation link above?

I would also prefer if you translate it as a public website (and link to that website from social media), since I want to link my blog post to your translated version as well, for Chinese speakers who read my blog. Perhaps can just use GitHub pages if you need to host it somewhere. Would this be possible?

Thanks

**Comment by weakish** [comment]
> I'm certainly okay for you to translate it

Glad to hear that.

> can you include links and attributions like the translation link above?

Of course.

> I would also prefer if you translate it as a public website

Actually there is a [public website][site]
(I said "under construction" because there will be a redesign of the site in next month.
I will post the translation on that site and post the url here.
And the urls shouldn't change after the redesign.
If it changed, I will make sure there would be a 301 redirection to the new url.)

Thanks and happy coding!

[site]: https://www.jqr.com/news/008222

**Comment by hardmaru** [comment]
Great, keep me updated later 👍

**Comment by weakish** [comment]
Translated [Recurrent Net Dreams Up Fake Chinese Characters in Vector Format with TensorFlow][rnn-vector-chars] to Chinese.

The link is https://www.jqr.com/news/008561

The link and attribution is at the bottom of the translated text,
and Otoro Studio is linked at the beginning of the translated text.

I omit some content in Chinese translation,
mainly the `sketch-rnn` setup section, since the README said that the project is deprecated.
And some knowledge about characters that are well known for Chinese speakers are also omitted.

Unfortunately the translated text is in Simplified Chinese.
Personally I think Traditional Chinese looks better than Simplified Chinese
(device with small font size is an exception).
But mostly readers in CN are more familiar with Simplified Chinese,
thus Simplified Chinese is used.

BTW, personally I cannot see the connection between Simplified Chinese and Newspeak.
But Simplified Chinese dose have some nasty bugs, like `(余, 餘)`, `(后, 後)`, `(适, 適)`, etc.

If you have any issue or question, please kindly let me know.

And thanks for your inspiring introduction to this interesting topic.

[rnn-vector-chars]: http://blog.otoro.net/2015/12/28/recurrent-net-dreams-up-fake-chinese-characters-in-vector-format-with-tensorflow/

**Comment by hardmaru** [comment]
Thanks for letting me know!

I’ll link the main article to your translation next time I update the blog.

I might have been a bit harsh on simplified Chinese to be honest ...

But it’s fun to point out the design flaws :-)

Like 愛 without a 心

**Comment by weakish** [comment]
Just translated [Neural Slime Volleyball][slime] into Chinese.

[slime]: http://blog.otoro.net/2015/03/28/neural-slime-volleyball/

The url is https://www.jqr.com/news/008677

> I might have been a bit harsh on simplified Chinese

Might not. I rethought your opinions and recalled
my struggling experience to start reading ancient Chinese books.
One of the main hassles is unable to recognise Traditional Chinese characters.
It was long ago thus I almost forgot it.
From this point, Simplified Chinese does have some sense of Newspeak,
as a hinder to access publications before the establishment of PRC.
But I am not sure if it is just a side effect or it was on purpose.

As for design flaws, I think
although "爱" without "心" breaks the traditional structure,
it is still acceptable,
since "友" (friendship) is somehow relevant in the meaning.
But there are a lot of nonsense simplifications, for example, the pattern "又".
For example, "鄧" has been simplified to "邓"
(breaking the phonetic relation between "登" and "鄧"),
and "聖" has been simplified to "圣"
(breaking the semantic relation),
making "邓" and "圣" harder to learn and memorise.
There are dozens of Chinese characters simplified with the pattern "又",
and there are several other patterns like "又".

**Comment by hardmaru** [comment]
Thanks for the translation, this article is a bit old- I updated the Kanji article to link to your translation one btw.

I was taught both Simplified and Traditional as a kid. I think my brain is somehow wired to recognise Traditional characters quicker, perhaps because there's more information and more "redundancy" in the way they are presented, from an information perspective.

**Comment by weakish** [comment]
Just finished translation of [Recurrent Neural Network Tutorial for Artists][1].

The url is https://www.jqr.com/news/008900

P.S. I am neither an artists nor a designer
(though one of my favourite books is "How to Design Programs"),
but I really enjoying this simple, clear, and inspiring demonstration on how to model handwriting.

[1]: http://blog.otoro.net/2017/01/01/recurrent-neural-network-artist/

**Comment by hardmaru** [comment]
The JavaScript code doesn’t seem to work on your site :)

**Comment by weakish** [comment]
> The JavaScript code doesn’t seem to work

Unfortunately the markdown editor used on jqr.com does not allow JavaScript. :-(

And the Chinese translation for the [neurogram][1] blog post:

https://www.jqr.com/news/008965

P.S. This web app is really cool.
To be honest, the slime volleyball app is also very cool,
but the too-hard-to-beat AI player let me feel hopeless very soon.
But with this one, I can let it evolve really interesting pictures.
It will be another time killer on my mobile device. 💓 

[1]: http://blog.otoro.net/2015/07/31/neurogram/

**Comment by weakish** [comment]
Excuse me, forgot to mention that there seems some typos in the blog post:

> ...to work on my NEAT implementation in __javascript__

Javascript
(not really a typo, just to be consistent to the spelling in the later part of the article)

> __CPPN’s__ are used to generate patterns

CPPNs

> A Backpropable __versiion__ of NEAT might be very interesting

version

**Comment by hardmaru** [comment]
Thanks

Have corrected -

**Comment by weakish** [comment]
I finished translating [Generating Abstract Patterns with TensorFlow][1] yesterday:

https://www.jqr.com/news/009203

Possible typos encountered during translation:

> and __contain__ 32 activations at each neural net layer

contains

> Let’s generate another random image __using the in the__ same latent space

I guess you meant either "using the same latent space" or "in the same latent space".

[1]: http://blog.otoro.net/2016/03/25/generating-abstract-patterns-with-tensorflow/

**Comment by hardmaru** [comment]
Thanks for the correction. I’ve fixed the errors now, appreciate it.

**Comment by weakish** [comment]
Hi, I translated Generating Large Images from Latent Vectors Part One[1] and Part Two[2]:

https://www.jqr.com/news/009358
https://www.jqr.com/news/009391

Some possible typos in Part One:

```python
z_1_before = sampler.encode(sampler.get_random_specific_mnist(1))
sampler.show_image_from_z(z_1_before)
z_1_after = sampler.encode(sampler.get_random_specific_mnist(1))
sampler.show_image_from_z(z_1_before)
```

`z_1_before` on the last line should be `z_1_after` instead.

```python
z_5_before = sampler.encode(sampler.get_random_specific_mnist(5))
sampler.show_image_from_z(z_5_before)
z_5_after = sampler.encode(sampler.get_random_specific_mnist(5))
sampler.show_image_from_z(z_5_before)
```

`z_5_before` on the last line should be `z_5_after` instead.

BTW, IDEs may not detect these typos because `z_{1, 5}_after`has been used in later code.
However, a paper[3] submitted to ICLR 2018 from MS Research
representing programs as graphs seems be able to detect these kind of typos
(at least for a statically typed language).

Some possible typos in Part Two:

> __resovoir__ computing

reservoir

> Current Model - 24 Epochs:

The video below is missing?

[1]: http://blog.otoro.net/2016/04/01/generating-large-images-from-latent-vectors/
[2]: http://blog.otoro.net/2016/06/02/generating-large-images-from-latent-vectors-part-two/
[3]: https://www.microsoft.com/en-us/research/wp-content/uploads/2017/11/programGraphs.pdf

**Comment by weakish** [comment]
Just translated Neural Network Evolution Playground with Backprop NEAT[0] to Chinese[1].

Enjoyed translating this gentle introduction to genetic algorithm and NEAT.
Design choices of the interactive demo are well explained in the article. Awesome!

A possible typo:

> Imagine if we have __a set of 100 random weights__ for a neural network

I guess you mean "100 sets of random wights"?

---

[0]: http://blog.otoro.net/2016/05/07/backprop-neat/
[1]: https://www.jqr.com/news/009466

**Comment by weakish** [comment]
I finished translation [0] of Teaching Machines to Draw [1] yesterday. ^_^

[0]: https://www.jqr.com/news/009523
[1]: http://blog.otoro.net/2017/05/19/teaching-machines-to-draw/

**Comment by hardmaru** [comment]
Thanks! I have fixed the typos, will push them out in a bit.

**Comment by weakish** [comment]
I translated [The Frog of CIFAR 10] and [Hyper Networks] to Chinese, the translated text is published at https://www.jqr.com/article/000013 and https://www.jqr.com/article/000037 correspondingly.

Possible typos in Hyper Networks:

> the weights a recurrent network

the weights of a recurrent network

**Comment by hardmaru** [comment]
Thanks for the catch! btw, you spelled "hardmu" in one of the posts-

**Comment by weakish** [comment]
> you spelled "hardmu"

Sorry. Fixed now.

**Comment by weakish** [comment]
Finished (abridged) translation of "world modules": https://www.jqr.com/article/000124

Enjoyed reading and translating this paper.
Awesome and inspiring.

**Comment by hardmaru** [comment]
Hi, thanks for the translation!

For this article, since it is not just me (but a joint work with my
coauthor), I request that you put:

The original URL, the URL of the arxiv pdf, and also the citation
information at the top of your article before your article content is
that’s fine.

Thanks!

**Comment by hardmaru** [comment]
Basically:

Original article URL: worldmodels.github.io

Arxiv URL (you have a link to it in your 1st paragraph but would like the URL to be displayed in its text, like arxiv.org/abs/....)

The BibTeX citation is in the original article in appendix.

**Comment by hardmaru** [comment]
Hi! I discussed w/ coauthor, it is okay not to include the BibTeX (just the other 2 URL). Thanks-

**Comment by weakish** [comment]
Sorry for the late reply (haven't checked GitHub during weekend).

I made the following edits:

1. Mention Schmidhuber in the translator's note
    (sorry for forgetting to mention him)
2. Add the worldmodels.github.io and arxiv.org link at the beginning
    (before first section "Introduction")
3. Add the BibTex citation at the end of the translated text

The online version is updated:

https://www.jqr.com/article/000124

If you see anything improper, or any room for improvements, please kindly let me know.

Thanks.

**Comment by hardmaru** [comment]
Thanks a lot, as always!
